/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Konstantin Koretskyi (https://sketchfab.com/cgnoobmaster)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ipad-pro-129-2020-f0f7674522124f3bbc2d0f898963457e
title: Ipad Pro 12.9 (2020)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Mac-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[12.65, 11.57, 1.52]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.Cube002_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[12.65, 10.31, 1.52]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.Cube003_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[10.79, 14.14, 1.03]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.Cube001_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[2.16, 0, -1.23]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.mainbody_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[2.16, 0, -1.23]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.screen_screen_0.geometry} material={materials.screen} />
          </group>
          <group position={[11.46, 11.59, 0.75]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.cameraconus2_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[11.46, 12.63, 0.75]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.cameraconus001_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[10.18, 12.9, 0.32]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.flashbody_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[10.19, 12.9, 0.29]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.flashglass_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[10.89, 12.1, 0.58]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.camerabody_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[10.98, 12.17, 0.49]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.cameramainglass_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[10.28, 11.2, 0.34]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.mic_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[10.28, 12.1, 0.32]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.sensor_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[11.49, 12.62, 0.65]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.Cube008_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[11.49, 11.58, 0.65]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.Cube009_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[11.45, 11.58, 0.81]} rotation={[-Math.PI / 2, 0, 2.89]} scale={70}>
            <mesh geometry={nodes.Sphere001_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[11.45, 12.62, 0.81]} rotation={[-Math.PI / 2, 0, 2.89]} scale={70}>
            <mesh geometry={nodes.Sphere002_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[2.16, -13.9, -1.23]} rotation={[-Math.PI / 2, 0, 2.89]} scale={100}>
            <mesh geometry={nodes.Cube005_mainbody_0.geometry} material={materials.mainbody} />
          </group>
          <group position={[2.17, -1.5, -1.26]} rotation={[Math.PI, 0.26, -Math.PI]} scale={1.02}>
            <mesh geometry={nodes.Apple001_logo_0.geometry} material={materials.logo} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Mac-transformed.glb')
